kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: new-joiner
rules:
- apiGroups: ["","apps",""] # Core API AND apps
  resources: ["*"]  # pods, services, deployments...
  verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner-role
subjects:
- kind: User
  name: oracle
roleRef:
  kind: ClusterRole
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
